
services:
  web:
    container_name: fronted-app
    restart: always
    build:
      context: ./tateti-fronted
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - server
    ports:
      - 4200:4200
    networks:
       - app-fullstack
  server :
    container_name: backend-app
    restart: always
    build:
      context: ./tateti-backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 5000
    ports:
      - 5000:5000
    networks:
      - app-fullstack
  nginx:
    
    container_name: load-balancer
    restart: always
    depends_on:
      - server
      - web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
       - 8080:80
    networks:
      - app-fullstack
  
networks:
  app-fullstack: